import React, { useState } from 'react';
import { marked } from 'marked';
import { TripFormData, TripResponse } from '../types';

interface TripResultProps {
  tripResult: (TripResponse & { pdf_link?: string; weather_data?: any; safety_info?: any }) | null;
  formData: TripFormData | null;
}

 const baseUrl = process.env.NODE_ENV === 'development' 
        ? "https://5fupmayclj.execute-api.ap-south-1.amazonaws.com/dev2"
        : "https://5fupmayclj.execute-api.ap-south-1.amazonaws.com/dev2";

const TripResult: React.FC<TripResultProps> = ({ tripResult, formData }) => {
  const [activeTab, setActiveTab] = useState('itinerary');
  const [audioLoading, setAudioLoading] = useState(false);

  const handleDownloadPDF = async () => {
    if (!tripResult) return;
    
    try {
      // const baseUrl = process.env.NODE_ENV === 'development' 
      //   ? 'http://127.0.0.1:8000' 
      //   : 'https://5fupmayclj.execute-api.ap-south-1.amazonaws.com/dev2';
      
      // Extract filename from pdf_link if available
      const pdfLink = (tripResult as any).pdf_link;
      if (pdfLink) {
        const filename = pdfLink.split('file=')[1];
        if (filename) {
          const response = await fetch(`${baseUrl}/download-pdf?file=${filename}`);
          if (response.ok) {
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);
            return;
          }
        }
      }
      
      alert('PDF not available. Please generate a new trip plan.');
    } catch (error) {
      console.error('PDF download error:', error);
      alert('Failed to download PDF. Please try again.');
    }
  };

  const handleAudioGeneration = async () => {
    if (!tripResult || !formData || audioLoading) return;
    
    setAudioLoading(true);
    
    try {
      // const baseUrl = process.env.NODE_ENV === 'development' 
      //   ? 'http://127.0.0.1:8000' 
      //   : 'https://5fupmayclj.execute-api.ap-south-1.amazonaws.com/dev2';
     
      const response = await fetch(`${baseUrl}/trip-audio?meta=1`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          text: tripResult.plan,
          mode: 'summary',
          tone: 'friendly'
        })
      });
      
      if (response.ok) {
        const data = await response.json();
        const audioUrl = `${baseUrl}${data.audio_url}`;
        
        const audio = new Audio(audioUrl);
        audio.controls = true;
        audio.style.width = '100%';
        audio.style.marginTop = '0.5rem';
        
        const audioContainer = document.createElement('div');
        audioContainer.innerHTML = `
          <div style="background: #f0fdf4; padding: 0.5rem; border-radius: 8px; margin-top: 0.5rem; border: 1px solid #bbf7d0;">
            <h4 style="color: #059669; margin-bottom: 0.5rem;">🎧 Audio Summary Generated</h4>
            <p style="color: #374151; font-size: 0.9rem; margin-bottom: 0.5rem;">Your trip summary is ready to listen!</p>
          </div>
        `;
        audioContainer.appendChild(audio);
        
        const controlsSection = document.querySelector('.controls-section');
        if (controlsSection && controlsSection.parentNode) {
          controlsSection.parentNode.insertBefore(audioContainer, controlsSection.nextSibling);
        }
      } else {
        alert('Failed to generate audio. Please try again.');
      }
    } catch (error) {
      console.error('Audio generation error:', error);
      alert('Failed to generate audio. Please try again.');
    } finally {
      setAudioLoading(false);
    }
  };

  const handleShareTrip = () => {
    if (!tripResult || !formData) return;
    
    const shareText = `🌍 ${formData.city} Trip Plan\n📅 ${formData.num_days} days, ${formData.no_of_persons} travelers\n💰 Budget: ${formData.budget_range}\n${formData.multi_cities.length > 0 ? `🗺️ Multi-city: ${formData.multi_cities.join(', ')}\n` : ''}\n✨ Generated by AskOxy AI Trip Planner\n🌐 askoxy.ai`;
    
    if (navigator.share) {
      navigator.share({
        title: `${formData.city} Trip Plan`,
        text: shareText,
        url: window.location.href
      }).catch(console.error);
    } else {
      navigator.clipboard.writeText(shareText).then(() => {
        alert('Trip details copied to clipboard!');
      }).catch(() => {
        const textArea = document.createElement('textarea');
        textArea.value = shareText;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        alert('Trip details copied to clipboard!');
      });
    }
  };

  if (!tripResult || !formData) {
    return (
      <div className="result-container">
        <div className="result-title">Your Perfect Trip Awaits ✈️</div>
        <p style={{ textAlign: 'center', fontSize: '1rem', color: '#94a3b8', marginBottom: '2rem' }}>
          Fill out the form to generate your personalized travel itinerary
        </p>
        
        <div className="preview-features">
          <div className="preview-card">
            <div className="preview-icon">📋</div>
            <h3>Complete Itinerary</h3>
            <p>Day-by-day plans with activities, dining, and attractions</p>
          </div>
          <div className="preview-card">
            <div className="preview-icon">💰</div>
            <h3>Smart Pricing</h3>
            <p>Real-time costs for flights, hotels, and activities</p>
          </div>
          <div className="preview-card">
            <div className="preview-icon">🛡️</div>
            <h3>Safety Info</h3>
            <p>Local safety ratings and emergency contacts</p>
          </div>
          <div className="preview-card">
            <div className="preview-icon">🌤️</div>
            <h3>Weather & Events</h3>
            <p>Forecasts and local events during your visit</p>
          </div>
        </div>
      </div>
    );
  }

  const currencySymbols: { [key: string]: string } = {
    'USD': '$', 'EUR': '€', 'GBP': '£', 'JPY': '¥', 'INR': '₹', 'CAD': 'C$', 'AUD': 'A$', 'CNY': '¥', 'SGD': 'S$', 'AED': 'د.إ'
  };
  const currencySymbol = currencySymbols[formData.currency] || '$';

  const renderTabContent = () => {
    switch (activeTab) {
      case 'itinerary':
        return (
          <div className="trip-content" 
               dangerouslySetInnerHTML={{ __html: marked(tripResult.plan || 'Trip plan generated successfully!') }} />
        );
      
      case 'pricing':
        const pricing = (tripResult as any).pricing_data?.estimated_costs;
        return (
          <div className="pricing-content">
            <h3>📊 Cost Breakdown</h3>
            <div className="cost-summary">
              <div className="cost-item">
                <span className="cost-label">✈️ Flights</span>
                <span className="cost-value">{currencySymbol}{pricing?.flights || '800'}</span>
              </div>
              <div className="cost-item">
                <span className="cost-label">🏨 Hotels</span>
                <span className="cost-value">{currencySymbol}{pricing?.accommodation || '600'}</span>
              </div>
              <div className="cost-item">
                <span className="cost-label">🎯 Activities</span>
                <span className="cost-value">{currencySymbol}{pricing?.activities || '200'}</span>
              </div>
              <div className="cost-item">
                <span className="cost-label">🚌 Transport</span>
                <span className="cost-value">{currencySymbol}{pricing?.transport || '150'}</span>
              </div>
              <div className="cost-item">
                <span className="cost-label">🍽️ Food</span>
                <span className="cost-value">{currencySymbol}{pricing?.food || '300'}</span>
              </div>
              {pricing?.multi_city > 0 && (
                <div className="cost-item">
                  <span className="cost-label">🗺️ Multi-City</span>
                  <span className="cost-value">{currencySymbol}{pricing.multi_city}</span>
                </div>
              )}
              <div className="cost-item total">
                <span className="cost-label"><strong>Total Est.</strong></span>
                <span className="cost-value"><strong>{currencySymbol}{pricing?.total || '2050'}</strong></span>
              </div>
            </div>
            {(tripResult as any).pricing_data?.group_discount > 0 && (
              <div className="company-offer">
                <h4>🎉 Group Discount Applied: {(tripResult as any).pricing_data.group_discount}% OFF</h4>
                <p>You're saving money by traveling as a group!</p>
              </div>
            )}
            <div className="company-offer">
              <h4>🎆 AskOxy Travel Packages</h4>
              <p>We offer pre-planned packages at competitive rates! Compare with our curated trips below.</p>
            </div>
          </div>
        );
      
      case 'packages':
        return (
          <div className="packages-content">
            <h3>🎆 AskOxy Travel - Pre-Planned Packages</h3>
            <p className="packages-intro">Choose from our expertly curated travel packages at unbeatable prices!</p>
            
            <div className="packages-grid">
              <div className="package-card budget">
                <div className="package-badge">BUDGET</div>
                <h4>{formData.city} Explorer</h4>
                <div className="package-price">{currencySymbol}{Math.round(((tripResult as any).pricing_data?.estimated_costs?.total || 2050) * 0.8)}</div>
                <div className="package-duration">{formData.num_days} Days • {formData.no_of_persons} Travelers</div>
                <ul className="package-features">
                  <li>✈️ Economy flights included</li>
                  <li>🏨 3-star hotel accommodation</li>
                  <li>🍽️ Daily breakfast</li>
                  <li>🗺️ City tour guide</li>
                  <li>📞 24/7 support</li>
                </ul>
                <button className="package-btn">Book Now</button>
              </div>
              
              <div className="package-card premium">
                <div className="package-badge">PREMIUM</div>
                <h4>{formData.city} Luxury</h4>
                <div className="package-price">{currencySymbol}{Math.round(((tripResult as any).pricing_data?.estimated_costs?.total || 2050) * 1.4)}</div>
                <div className="package-duration">{formData.num_days} Days • {formData.no_of_persons} Travelers</div>
                <ul className="package-features">
                  <li>✈️ Business class flights</li>
                  <li>🏨 5-star luxury hotels</li>
                  <li>🍽️ All meals included</li>
                  <li>🚗 Private transfers</li>
                  <li>🎭 Premium experiences</li>
                </ul>
                <button className="package-btn premium-btn">Book Premium</button>
              </div>
              
              <div className="package-card custom">
                <div className="package-badge">CUSTOM</div>
                <h4>Your Custom Plan</h4>
                <div className="package-price">Let's Plan Together</div>
                <div className="package-duration">Tailored to You</div>
                <ul className="package-features">
                  <li>🎯 Personalized itinerary</li>
                  <li>💰 Flexible budget options</li>
                  <li>🗺️ Local expert guidance</li>
                  <li>📞 Dedicated travel consultant</li>
                  <li>✨ Unique experiences</li>
                </ul>
                <button className="package-btn custom-btn">Contact Us</button>
              </div>
            </div>
            
            <div className="company-contact">
              <h4>📞 Ready to Book? Contact AskOxy Travel</h4>
              <div className="contact-info">
                <span>📧 travel@askoxy.ai</span>
                <span>📞 +1 (555) ASKOXY</span>
                <span>🌐 www.askoxy.ai/travel</span>
              </div>
            </div>
          </div>
        );
      
      case 'weather':
        const weather = (tripResult as any).weather_data;
        return (
          <div className="weather-content">
            <h3>🌡️ Weather Forecast</h3>
            {weather?.travel_month && (
              <p style={{textAlign: 'center', marginBottom: '1rem', color: '#6b7280'}}>
                📅 Travel Month: {weather.travel_month}
              </p>
            )}
            <div className="weather-card">
              <div className="weather-main">
                <span className="temp">{weather?.current?.temperature || 22}°C</span>
                <span className="condition">{weather?.current?.condition || 'Partly Cloudy'}</span>
              </div>
              <div className="weather-details">
                <span>💧 Humidity: {weather?.current?.humidity || 65}%</span>
                <span>🌬️ Wind: {weather?.current?.wind_speed || 12} km/h</span>
              </div>
            </div>
            {weather?.forecast && (
              <div style={{marginTop: '1rem'}}>
                <h4 style={{color: '#374151', marginBottom: '0.5rem'}}>5-Day Forecast</h4>
                <div style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))', gap: '0.5rem'}}>
                  {weather.forecast.slice(0, 5).map((day: any, index: number) => (
                    <div key={index} style={{background: '#f8fafc', padding: '0.5rem', borderRadius: '6px', textAlign: 'center'}}>
                      <div style={{fontSize: '1.2rem'}}>{day.icon}</div>
                      <div style={{fontSize: '0.8rem', fontWeight: '600'}}>{day.day}</div>
                      <div style={{fontSize: '0.75rem', color: '#6b7280'}}>{day.high}°/{day.low}°</div>
                    </div>
                  ))}
                </div>
              </div>
            )}
            <p className="weather-tip">🌟 {weather?.best_time || 'Spring and Fall offer pleasant weather'}</p>
          </div>
        );
      
      case 'safety':
        const safety = (tripResult as any).safety_info;
        return (
          <div className="safety-content">
            <h3>🛡️ Safety Information</h3>
            <div className="safety-rating">
              <h4>Safety Rating: {safety?.safety_rating || 8}/10</h4>
              <p>{safety?.travel_advisory || 'Generally safe for tourists with standard precautions'}</p>
              <p style={{color: '#6b7280', fontSize: '0.9rem'}}>Crime Level: {safety?.crime_level || 'Low to Moderate'}</p>
            </div>
            
            {safety?.current_alerts && safety.current_alerts.length > 0 && (
              <div style={{background: '#fef3c7', padding: '1rem', borderRadius: '8px', margin: '1rem 0', border: '1px solid #f59e0b'}}>
                <h4 style={{color: '#d97706', margin: '0 0 0.5rem 0'}}>⚠️ Current Alerts</h4>
                {safety.current_alerts.map((alert: string, index: number) => (
                  <p key={index} style={{color: '#92400e', fontSize: '0.9rem', margin: '0.25rem 0'}}>{alert}</p>
                ))}
              </div>
            )}
            
            <div className="safety-tips">
              <h4>📝 Safety Tips:</h4>
              <ul>
                {safety?.safe_areas && (
                  <li><strong>Safe Areas:</strong> {safety.safe_areas.join(', ')}</li>
                )}
                {safety?.avoid_areas && (
                  <li><strong>Avoid:</strong> {safety.avoid_areas.join(', ')}</li>
                )}
                {safety?.common_scams && (
                  <li><strong>Common Scams:</strong> {safety.common_scams.join(', ')}</li>
                )}
              </ul>
              
              {safety?.emergency_numbers && (
                <div style={{background: '#f0fdf4', padding: '1rem', borderRadius: '8px', marginTop: '1rem'}}>
                  <h4 style={{color: '#059669', margin: '0 0 0.5rem 0'}}>🆘 Emergency Numbers</h4>
                  <div style={{display: 'flex', gap: '1rem', flexWrap: 'wrap'}}>
                    <span>🚑 Police: {safety.emergency_numbers.police}</span>
                    <span>🏥 Medical: {safety.emergency_numbers.medical}</span>
                    <span>🚒 Fire: {safety.emergency_numbers.fire}</span>
                  </div>
                </div>
              )}
            </div>
          </div>
        );
      
      default:
        return null;
    }
  };

  return (
    <div className="result-container">
      <div className="result-content">
        <div className="result-header">
          <h2>🌍 {formData.budget_range.charAt(0).toUpperCase() + formData.budget_range.slice(1)} Trip to {formData.city}</h2>
          <div className="trip-summary">
            <span className="summary-item">📅 {formData.num_days} Days</span>
            <span className="summary-item">👥 {formData.no_of_persons} Travelers</span>
            <span className="summary-item">💰 {formData.currency}</span>
            {formData.multi_cities.length > 0 && <span className="summary-item">🗺️ Multi-City</span>}
          </div>
        </div>
        
        <div className="result-body">
          <div className="trip-tabs">
            <button 
              className={`tab-btn ${activeTab === 'itinerary' ? 'active' : ''}`}
              onClick={() => setActiveTab('itinerary')}
            >
              📋 Itinerary
            </button>
            <button 
              className={`tab-btn ${activeTab === 'pricing' ? 'active' : ''}`}
              onClick={() => setActiveTab('pricing')}
            >
              💰 Pricing
            </button>
            {/* <button 
              className={`tab-btn ${activeTab === 'packages' ? 'active' : ''}`}
              onClick={() => setActiveTab('packages')}
            >
              🎆 Our Packages
            </button> */}
            <button 
              className={`tab-btn ${activeTab === 'weather' ? 'active' : ''}`}
              onClick={() => setActiveTab('weather')}
            >
              🌤️ Weather
            </button>
            <button 
              className={`tab-btn ${activeTab === 'safety' ? 'active' : ''}`}
              onClick={() => setActiveTab('safety')}
            >
              🛡️ Safety
            </button>
          </div>
          
          <div className="tab-content">
            {renderTabContent()}
          </div>
        </div>
        
        <div className="controls-section">
          <div className="action-buttons">
            <button className="action-btn" onClick={handleDownloadPDF}>💾 Download PDF</button>
            <button className="action-btn audio" onClick={handleAudioGeneration} disabled={audioLoading}>
              {audioLoading ? '⏳ Generating...' : '🎧 Audio Summary'}
            </button>
            <button className="action-btn" style={{ background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)' }} onClick={handleShareTrip}>📤 Share Trip</button>
            {/* <button 
              className="action-btn" 
              style={{ background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)' }}
              onClick={() => setActiveTab('packages')}
            >
              🎆 View Our Packages
            </button> */}
          </div>
        </div>
      </div>
    </div>
  );
};

export default TripResult;