import React from "react";

type ContentBlock = {
  kind: "paragraph" | "subheading" | "bullet";
  text: string;
};

type LegalSection = {
  number: string;
  title: string;
  id: string;
  blocks: ContentBlock[];
};

const sections: LegalSection[] = [
  {
    "number": "1",
    "title": "Interpretation and Definitions",
    "id": "interpretation-and-definitions",
    "blocks": [
      {
        "kind": "subheading",
        "text": "Interpretation"
      },
      {
        "kind": "paragraph",
        "text": "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
      },
      {
        "kind": "subheading",
        "text": "Definitions"
      },
      {
        "kind": "paragraph",
        "text": "For the purposes of this Privacy Policy:"
      },
      {
        "kind": "paragraph",
        "text": "Account: means a unique account created for You to access our Service or parts of our Service."
      },
      {
        "kind": "paragraph",
        "text": "Affiliate: means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority."
      },
      {
        "kind": "paragraph",
        "text": "Application: refers to ASKOXY.AI, the software program provided by the Company."
      },
      {
        "kind": "paragraph",
        "text": "Company: refers to OXYKART TECHNOLOGIES PVT LTD, CC-02, Ground Floor, Indu Fortune Fields, KPHB Colony, Hyderabad, Telangana - 500085."
      },
      {
        "kind": "paragraph",
        "text": "Country: refers to India."
      },
      {
        "kind": "paragraph",
        "text": "Data Fiduciary: means the Company where it determines the purpose and means of processing Personal Data."
      },
      {
        "kind": "paragraph",
        "text": "Data Principal: means the individual to whom the Personal Data relates."
      },
      {
        "kind": "paragraph",
        "text": "Device: means any device that can access the Service such as a computer, a cell phone or a digital tablet."
      },
      {
        "kind": "paragraph",
        "text": "Personal Data: means any data about an individual who is identifiable by or in relation to such data."
      },
      {
        "kind": "paragraph",
        "text": "Service: refers to the Application and services provided through Aksoxy.ai."
      },
      {
        "kind": "paragraph",
        "text": "Service Provider: means any natural or legal person who processes Personal Data on behalf of the Company."
      },
      {
        "kind": "paragraph",
        "text": "Third-party Social Media Service: means any website or social network website through which a User can log in or create an account to use the Service."
      },
      {
        "kind": "paragraph",
        "text": "Usage Data: refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself."
      },
      {
        "kind": "paragraph",
        "text": "You: means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
      }
    ]
  },
  {
    "number": "2",
    "title": "Collecting and Using Your Personal Data",
    "id": "collecting-and-using-your-personal-data",
    "blocks": [
      {
        "kind": "subheading",
        "text": "Types of Data Collected"
      },
      {
        "kind": "subheading",
        "text": "Personal Data"
      },
      {
        "kind": "paragraph",
        "text": "While using Our Service, We may ask You to provide Personal Data necessary for the relevant Service or feature. The Personal Data collected may vary depending on the Service, transaction, request, or functionality used by You."
      },
      {
        "kind": "paragraph",
        "text": "Personal Data may include, but is not limited to:"
      },
      {
        "kind": "bullet",
        "text": "Email address and password"
      },
      {
        "kind": "bullet",
        "text": "First name and Last name"
      },
      {
        "kind": "bullet",
        "text": "Phone number"
      },
      {
        "kind": "bullet",
        "text": "Address, State, Province, ZIP/Postal code, City"
      },
      {
        "kind": "bullet",
        "text": "Payment information (credit/debit cards, UPI, wallets)"
      },
      {
        "kind": "bullet",
        "text": "Profile pictures and uploaded photos"
      },
      {
        "kind": "bullet",
        "text": "Government-issued ID for applicable verification"
      },
      {
        "kind": "bullet",
        "text": "Bank account details where required for applicable services"
      },
      {
        "kind": "bullet",
        "text": "GST/Tax information for applicable business services"
      },
      {
        "kind": "bullet",
        "text": "Emergency contact information where required"
      },
      {
        "kind": "bullet",
        "text": "Service-specific information required for lending, employment, study abroad consultation, fractional ownership, gold-related services, AI-powered services, cryptocurrency or blockchain services, marketplace services, or other services offered through the platform"
      },
      {
        "kind": "subheading",
        "text": "Device Permissions & Media Access"
      },
      {
        "kind": "paragraph",
        "text": "Our Service may request access to device features or media where required for a specific functionality or service."
      },
      {
        "kind": "subheading",
        "text": "📷 Camera Access"
      },
      {
        "kind": "bullet",
        "text": "Profile picture capture"
      },
      {
        "kind": "bullet",
        "text": "Product/order photos for quality feedback"
      },
      {
        "kind": "bullet",
        "text": "Delivery verification photos"
      },
      {
        "kind": "bullet",
        "text": "Document scanning for applicable verification"
      },
      {
        "kind": "bullet",
        "text": "Issue reporting with visual evidence"
      },
      {
        "kind": "subheading",
        "text": "📍 Location Services"
      },
      {
        "kind": "bullet",
        "text": "Real-time delivery tracking"
      },
      {
        "kind": "bullet",
        "text": "Finding nearby restaurants/stores"
      },
      {
        "kind": "bullet",
        "text": "Accurate address detection"
      },
      {
        "kind": "bullet",
        "text": "Delivery route optimization"
      },
      {
        "kind": "bullet",
        "text": "Location-based recommendations"
      },
      {
        "kind": "subheading",
        "text": "🖼️ Photo & Video Storage"
      },
      {
        "kind": "bullet",
        "text": "Accessing gallery for profile pictures"
      },
      {
        "kind": "bullet",
        "text": "Uploading food/product images"
      },
      {
        "kind": "bullet",
        "text": "Sharing delivery experience videos"
      },
      {
        "kind": "bullet",
        "text": "Storing delivery proof photos"
      },
      {
        "kind": "bullet",
        "text": "Uploading documents or other content where required by a service"
      },
      {
        "kind": "subheading",
        "text": "📞 Communication Access"
      },
      {
        "kind": "bullet",
        "text": "Phone calls for order support"
      },
      {
        "kind": "bullet",
        "text": "SMS for order updates"
      },
      {
        "kind": "bullet",
        "text": "Push notifications"
      },
      {
        "kind": "bullet",
        "text": "In-app messaging"
      },
      {
        "kind": "bullet",
        "text": "Service-related communications"
      },
      {
        "kind": "subheading",
        "text": "Usage Data"
      },
      {
        "kind": "paragraph",
        "text": "Usage Data is collected automatically when using the Service. This may include IP address, browser type, device identifiers, pages visited, time spent, search queries, order history, preferences, app interactions, crash reports, performance metrics, and technical information. Location data may include GPS coordinates, Wi-Fi access points, and cell tower information when location services are enabled."
      },
      {
        "kind": "subheading",
        "text": "Third-Party Data"
      },
      {
        "kind": "paragraph",
        "text": "We may receive information from third-party services when You connect an account, use an integrated service, or complete a transaction through a third party, including:"
      },
      {
        "kind": "bullet",
        "text": "Social media profile information"
      },
      {
        "kind": "bullet",
        "text": "Google/Facebook account information"
      },
      {
        "kind": "bullet",
        "text": "Payment gateway transaction data"
      },
      {
        "kind": "bullet",
        "text": "Analytics and advertising partner information"
      },
      {
        "kind": "bullet",
        "text": "Restaurant/store partner information"
      },
      {
        "kind": "bullet",
        "text": "Logistics and mapping information"
      },
      {
        "kind": "bullet",
        "text": "Service-specific information from applicable verification, financial, employment, educational, marketplace, or other service partners"
      },
      {
        "kind": "subheading",
        "text": "Use of Your Personal Data"
      },
      {
        "kind": "paragraph",
        "text": "The Company may use Personal Data for the following purposes:"
      },
      {
        "kind": "bullet",
        "text": "To provide and maintain our Service, including account, order, transaction, and service processing"
      },
      {
        "kind": "bullet",
        "text": "To manage Your Account and authenticate Your identity"
      },
      {
        "kind": "bullet",
        "text": "To process payments, refunds, billing, and applicable financial transactions"
      },
      {
        "kind": "bullet",
        "text": "To provide customer support and respond to inquiries"
      },
      {
        "kind": "bullet",
        "text": "To send order confirmations, delivery updates, and service notifications"
      },
      {
        "kind": "bullet",
        "text": "To provide location-based and delivery-related services"
      },
      {
        "kind": "bullet",
        "text": "To facilitate photo and video uploads, document submissions, and service-related verification"
      },
      {
        "kind": "bullet",
        "text": "To provide IP2PL — Peer-to-Peer Lending services"
      },
      {
        "kind": "bullet",
        "text": "To provide JPL — Jobs and employment-related services"
      },
      {
        "kind": "bullet",
        "text": "To provide SAPL — Study Abroad Consultation services"
      },
      {
        "kind": "bullet",
        "text": "To provide FPL — Fractional Ownership services"
      },
      {
        "kind": "bullet",
        "text": "To provide GPL — Gold-related services"
      },
      {
        "kind": "bullet",
        "text": "To provide AIPL — Bharat AI Store products and services"
      },
      {
        "kind": "bullet",
        "text": "To provide Free AI Generation Tools and related AI-powered services"
      },
      {
        "kind": "bullet",
        "text": "To provide cryptocurrency and blockchain-related services"
      },
      {
        "kind": "bullet",
        "text": "To verify information and perform applicable KYC, compliance, fraud-prevention, or security checks"
      },
      {
        "kind": "bullet",
        "text": "To prevent fraud, misuse, unauthorised access, and other security threats"
      },
      {
        "kind": "bullet",
        "text": "To analyze usage, diagnose technical issues, and improve our products and services"
      },
      {
        "kind": "bullet",
        "text": "To provide recommendations, relevant content, and service-related offers"
      },
      {
        "kind": "bullet",
        "text": "To send promotional communications where the required consent or other lawful basis is applicable"
      },
      {
        "kind": "bullet",
        "text": "To manage relationships with service providers, business partners, merchants, and other parties involved in providing the requested service"
      },
      {
        "kind": "bullet",
        "text": "To conduct research, analytics, feedback, and service improvement activities"
      },
      {
        "kind": "bullet",
        "text": "To comply with applicable laws, regulations, legal processes, and governmental requirements"
      },
      {
        "kind": "bullet",
        "text": "To establish, exercise, or defend legal claims and resolve disputes"
      },
      {
        "kind": "bullet",
        "text": "To manage mergers, acquisitions, restructuring, financing, or other business transfers"
      }
    ]
  },
  {
    "number": "3",
    "title": "Data Sharing and Disclosure",
    "id": "data-sharing-and-disclosure",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "We may share Personal Data with the following categories of recipients where necessary for the relevant purpose or service:"
      },
      {
        "kind": "paragraph",
        "text": "Service Providers: With payment processors, cloud and hosting providers, delivery partners, technical service providers, analytics providers, communication providers, and other service providers processing Personal Data on our behalf."
      },
      {
        "kind": "paragraph",
        "text": "Business Partners: With relevant merchants, restaurants, stores, lending, employment, education, financial, marketplace, logistics, verification, or other service partners where necessary to provide the requested service."
      },
      {
        "kind": "paragraph",
        "text": "Legal Requirements: When required or authorised by applicable law, court orders, governmental or regulatory authorities, or for the protection of our legal rights, users, property, or safety."
      },
      {
        "kind": "paragraph",
        "text": "Business Transfers: In connection with mergers, acquisitions, restructuring, financing, sale, or transfer of assets or business operations."
      },
      {
        "kind": "paragraph",
        "text": "Consent: Where sharing is based on consent, in accordance with the applicable consent provided."
      },
      {
        "kind": "paragraph",
        "text": "Emergency Situations: Where necessary to respond to an emergency or protect the safety of individuals or the public."
      },
      {
        "kind": "paragraph",
        "text": "We require applicable service providers and processors handling Personal Data on our behalf to maintain appropriate safeguards and process such data in accordance with applicable requirements and contractual obligations."
      }
    ]
  },
  {
    "number": "4",
    "title": "Retention of Your Personal Data",
    "id": "retention-of-your-personal-data",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "The Company will retain Your Personal Data for the period necessary to provide the relevant Service, fulfil the purposes described in this Privacy Policy, comply with applicable legal and regulatory requirements, resolve disputes, maintain security, and enforce our agreements."
      },
      {
        "kind": "subheading",
        "text": "Retention Periods:"
      },
      {
        "kind": "bullet",
        "text": "Account information: Until account deletion + 30 days"
      },
      {
        "kind": "bullet",
        "text": "Order history: 7 years for tax and legal compliance"
      },
      {
        "kind": "bullet",
        "text": "Payment data: As required by applicable payment, tax, accounting, or regulatory requirements"
      },
      {
        "kind": "bullet",
        "text": "Photos/videos: 90 days after order completion, unless required for an active dispute, investigation, legal obligation, or applicable service requirement"
      },
      {
        "kind": "bullet",
        "text": "Location data: 30 days for active orders, anonymized thereafter where applicable"
      },
      {
        "kind": "bullet",
        "text": "Communication logs: 2 years for customer service and dispute-related purposes"
      },
      {
        "kind": "bullet",
        "text": "Usage analytics: 3 years in anonymized form"
      },
      {
        "kind": "bullet",
        "text": "Service-specific Personal Data: For the period required to provide the applicable service and meet applicable legal, regulatory, contractual, security, or dispute-resolution requirements"
      }
    ]
  },
  {
    "number": "5",
    "title": "Data Storage and Security",
    "id": "data-storage-and-security",
    "blocks": [
      {
        "kind": "subheading",
        "text": "Local Data Storage"
      },
      {
        "kind": "paragraph",
        "text": "Your Personal Data is processed and stored on secure servers located within India. Where Personal Data is processed or transferred outside India through service providers or other arrangements, such processing or transfer will be subject to applicable law and safeguards."
      },
      {
        "kind": "subheading",
        "text": "Security Measures"
      },
      {
        "kind": "bullet",
        "text": "End-to-end encryption for sensitive data transmission"
      },
      {
        "kind": "bullet",
        "text": "Encryption, masking, obfuscation, or tokenisation of Personal Data where appropriate"
      },
      {
        "kind": "bullet",
        "text": "Secure server infrastructure with regular updates"
      },
      {
        "kind": "bullet",
        "text": "Multi-factor authentication for administrative access"
      },
      {
        "kind": "bullet",
        "text": "Access controls and role-based permissions"
      },
      {
        "kind": "bullet",
        "text": "Logging, monitoring, and review of access to Personal Data"
      },
      {
        "kind": "bullet",
        "text": "Regular security audits and penetration testing"
      },
      {
        "kind": "bullet",
        "text": "Encrypted storage for photos, videos, and documents"
      },
      {
        "kind": "bullet",
        "text": "Backup and disaster recovery procedures"
      },
      {
        "kind": "bullet",
        "text": "Security and data-protection training for relevant personnel"
      },
      {
        "kind": "bullet",
        "text": "PCI DSS compliance for applicable payment processing"
      },
      {
        "kind": "bullet",
        "text": "Monitoring for suspicious activities and unauthorised access"
      },
      {
        "kind": "bullet",
        "text": "Reasonable technical and organisational measures to protect Personal Data against unauthorised access, alteration, disclosure, loss, destruction, or other security risks"
      },
      {
        "kind": "bullet",
        "text": "Appropriate contractual safeguards for service providers and processors handling Personal Data"
      },
      {
        "kind": "paragraph",
        "text": "Important Note: While we implement robust security measures, no method of transmission over the Internet is 100% secure. We continuously update our security practices and encourage users to use strong passwords and enable two-factor authentication."
      },
      {
        "kind": "subheading",
        "text": "Personal Data Breach"
      },
      {
        "kind": "paragraph",
        "text": "In the event of a Personal Data breach, we will take appropriate measures to detect, contain, investigate, mitigate, and remediate the breach. Where required by applicable law, affected Data Principals and the relevant authority will be notified within the applicable timelines and with the information required under applicable law."
      }
    ]
  },
  {
    "number": "6",
    "title": "Your Data Principal Rights",
    "id": "your-data-principal-rights",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "Under applicable data protection laws, including the Digital Personal Data Protection Act, 2023 as and when its relevant provisions apply, You may have the following rights:"
      },
      {
        "kind": "paragraph",
        "text": "Right to Access: Request information about whether Your Personal Data is being processed and obtain applicable information regarding such processing."
      },
      {
        "kind": "paragraph",
        "text": "Right to Correction: Request correction of inaccurate or incomplete Personal Data."
      },
      {
        "kind": "paragraph",
        "text": "Right to Erasure: Request deletion of Personal Data where permitted under applicable law."
      },
      {
        "kind": "paragraph",
        "text": "Right to Withdraw Consent: Withdraw consent where processing is based on consent, subject to applicable law and the consequences of withdrawal."
      },
      {
        "kind": "paragraph",
        "text": "Right to Grievance Redressal: Raise a grievance regarding the processing or handling of Your Personal Data."
      },
      {
        "kind": "paragraph",
        "text": "Right to Nominate: Nominate another individual to exercise applicable rights on Your behalf in accordance with applicable law."
      },
      {
        "kind": "paragraph",
        "text": "Right to Data Portability: Where provided by applicable law, request transfer or portability of Your Personal Data in the prescribed manner."
      },
      {
        "kind": "paragraph",
        "text": "Right to Restrict Processing: Where provided by applicable law, request restriction of processing of Your Personal Data."
      },
      {
        "kind": "paragraph",
        "text": "Right to Object: Where provided by applicable law, object to processing for applicable purposes, including direct marketing."
      },
      {
        "kind": "paragraph",
        "text": "Right to Manage Permissions: Manage device permissions such as camera, location, and media access through available device or application controls."
      },
      {
        "kind": "paragraph",
        "text": "Requests may be subject to identity verification and applicable legal limitations or exceptions."
      }
    ]
  },
  {
    "number": "7",
    "title": "Cookies and Tracking Technologies",
    "id": "cookies-and-tracking-technologies",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "We use cookies and similar tracking technologies to operate the Service, maintain security, remember preferences, analyze usage, and provide relevant services."
      },
      {
        "kind": "subheading",
        "text": "Types of Cookies and Tracking:"
      },
      {
        "kind": "paragraph",
        "text": "Essential Cookies: Required for login, cart functionality, security, and basic operations"
      },
      {
        "kind": "paragraph",
        "text": "Performance Cookies: Collect information about application usage and performance"
      },
      {
        "kind": "paragraph",
        "text": "Functional Cookies: Remember preferences, language settings, and relevant service preferences"
      },
      {
        "kind": "paragraph",
        "text": "Analytics Cookies: Help us understand user behaviour and improve our services"
      },
      {
        "kind": "paragraph",
        "text": "Marketing Cookies: Used for advertising and promotional activities where applicable"
      },
      {
        "kind": "paragraph",
        "text": "Location Tracking: GPS and network-based location information for delivery and other location-enabled services"
      },
      {
        "kind": "paragraph",
        "text": "Device Fingerprinting: Technical device information may be used for security and fraud-prevention purposes where applicable"
      },
      {
        "kind": "paragraph",
        "text": "You can manage cookies through your browser settings or available application controls. Disabling certain cookies or technologies may affect the availability of some Service features."
      }
    ]
  },
  {
    "number": "8",
    "title": "Children's Privacy",
    "id": "children-s-privacy",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "Our Service is not intended for children where the processing is prohibited or restricted under applicable law. We do not knowingly process children's Personal Data except in accordance with applicable legal requirements and safeguards."
      },
      {
        "kind": "paragraph",
        "text": "Where applicable law requires parental or lawful guardian consent or additional safeguards for processing children's Personal Data, we will implement the required measures."
      },
      {
        "kind": "paragraph",
        "text": "If You believe that Personal Data of a child has been collected or processed in violation of applicable requirements, please contact us using the details provided in this Privacy Policy."
      }
    ]
  },
  {
    "number": "9",
    "title": "Changes to this Privacy Policy",
    "id": "changes-to-this-privacy-policy",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "We may update Our Privacy Policy from time to time. We will notify You of material changes by posting the updated Privacy Policy on this page and updating the \"Last updated\" date."
      },
      {
        "kind": "subheading",
        "text": "How We Notify You:"
      },
      {
        "kind": "bullet",
        "text": "Email notification to registered users"
      },
      {
        "kind": "bullet",
        "text": "In-app notifications for significant changes"
      },
      {
        "kind": "bullet",
        "text": "Prominent notice on our website"
      },
      {
        "kind": "bullet",
        "text": "Push notifications for policy updates"
      },
      {
        "kind": "bullet",
        "text": "Updated date at the top of this policy"
      },
      {
        "kind": "paragraph",
        "text": "Where a change requires a new privacy notice, consent, or other user action under applicable law, the applicable notice or action will be provided separately."
      },
      {
        "kind": "paragraph",
        "text": "Continued use of our Service after changes indicates acceptance of the updated Privacy Policy."
      }
    ]
  },
  {
    "number": "10",
    "title": "International Data Transfers",
    "id": "international-data-transfers",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "Your information, including Personal Data, is processed and stored within India. We do not transfer your personal data to countries outside India except in the following limited circumstances:"
      },
      {
        "kind": "bullet",
        "text": "Third-party service providers with adequate data protection measures"
      },
      {
        "kind": "bullet",
        "text": "Legal requirements or court orders from recognized jurisdictions"
      },
      {
        "kind": "bullet",
        "text": "Your explicit consent for specific international services"
      },
      {
        "kind": "bullet",
        "text": "Emergency situations to protect user safety"
      },
      {
        "kind": "paragraph",
        "text": "When international transfers are necessary, we ensure appropriate safeguards are in place to protect your data."
      },
      {
        "kind": "paragraph",
        "text": "Where Personal Data is processed or transferred outside India through service providers or other arrangements, such processing or transfer will be carried out in accordance with applicable Indian law and any applicable restrictions or safeguards."
      }
    ]
  },
  {
    "number": "11",
    "title": "Complaint Resolution & Grievance Officer",
    "id": "complaint-resolution-grievance-officer",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "If You have any concerns regarding the collection, use, sharing, security, or handling of Your Personal Data, You can contact our Grievance Officer:"
      },
      {
        "kind": "subheading",
        "text": "Grievance Officer Details:"
      },
      {
        "kind": "paragraph",
        "text": "Name: Grievance Officer"
      },
      {
        "kind": "paragraph",
        "text": "Email: support@askoxy.ai"
      },
      {
        "kind": "paragraph",
        "text": "Phone: +91-814-327-1103"
      },
      {
        "kind": "paragraph",
        "text": "We are committed to resolving your concerns within 30 days of receiving your complaint."
      }
    ]
  },
  {
    "number": "12",
    "title": "Contact Us",
    "id": "contact-us",
    "blocks": [
      {
        "kind": "paragraph",
        "text": "If You have any questions about this Privacy Policy, data handling, consent, or privacy practices, You can contact us:"
      },
      {
        "kind": "paragraph",
        "text": "Email: support@askoxy.ai"
      },
      {
        "kind": "paragraph",
        "text": "Phone: +91-814-327-1103"
      },
      {
        "kind": "paragraph",
        "text": "Phone: +91-911-056-4106"
      },
      {
        "kind": "paragraph",
        "text": "Address: OXYKART TECHNOLOGIES PVT LTD, CC-02, Ground Floor, Indu Fortune Fields, KPHB Colony, Hyderabad, Telangana - 500085"
      },
      {
        "kind": "paragraph",
        "text": "Website: www.askoxy.ai"
      },
      {
        "kind": "paragraph",
        "text": "Business Hours: Monday to Friday, 9:00 AM to 6:00 PM (IST)"
      },
      {
        "kind": "paragraph",
        "text": "Emergency Support: Available 24/7 for critical privacy concerns"
      }
    ]
  }
];

const linkifyValue = (label: string, value: string): React.ReactNode => {
  const normalizedLabel = label.toLowerCase();

  if (normalizedLabel.startsWith("email")) {
    return (
      <a
        href={`mailto:${value}`}
        className="font-medium text-blue-700 underline decoration-blue-200 underline-offset-2 hover:text-blue-800"
      >
        {value}
      </a>
    );
  }

  if (normalizedLabel.startsWith("phone")) {
    const phone = value.replace(/[^\d+]/g, "");
    return (
      <a
        href={`tel:${phone}`}
        className="font-medium text-blue-700 underline decoration-blue-200 underline-offset-2 hover:text-blue-800"
      >
        {value}
      </a>
    );
  }

  if (normalizedLabel.startsWith("website")) {
    const href = /^https?:\/\//i.test(value) ? value : `https://${value}`;
    return (
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        className="break-all font-medium text-blue-700 underline decoration-blue-200 underline-offset-2 hover:text-blue-800"
      >
        {value}
      </a>
    );
  }

  return value;
};

const renderText = (text: string): React.ReactNode => {
  const colonIndex = text.indexOf(":");

  if (colonIndex > 0 && colonIndex <= 55) {
    const label = text.slice(0, colonIndex).trim();
    const value = text.slice(colonIndex + 1).trim();

    if (label && value) {
      return (
        <>
          <strong className="font-semibold text-slate-900">{label}:</strong>{" "}
          {linkifyValue(label, value)}
        </>
      );
    }
  }

  return text;
};

const renderBlocks = (blocks: ContentBlock[]) => {
  const output: React.ReactNode[] = [];
  let bullets: string[] = [];

  const flushBullets = () => {
    if (!bullets.length) return;

    const items = bullets;
    bullets = [];

    output.push(
      <ul
        key={`bullets-${output.length}`}
        className="my-4 space-y-2.5 rounded-xl border border-slate-200 bg-slate-50/70 p-4 sm:p-5"
      >
        {items.map((item, index) => (
          <li
            key={`${item}-${index}`}
            className="flex min-w-0 items-start gap-3 text-sm leading-6 text-slate-700 sm:text-[15px] sm:leading-7"
          >
            <span
              aria-hidden="true"
              className="mt-[9px] h-1.5 w-1.5 shrink-0 rounded-full bg-blue-600"
            />
            <span className="min-w-0 break-words [overflow-wrap:anywhere]">
              {renderText(item)}
            </span>
          </li>
        ))}
      </ul>,
    );
  };

  blocks.forEach((block, index) => {
    if (block.kind === "bullet") {
      bullets.push(block.text);
      return;
    }

    flushBullets();

    if (block.kind === "subheading") {
      output.push(
        <h3
          key={`${block.text}-${index}`}
          className="mb-2 mt-6 text-base font-semibold leading-snug text-slate-900 sm:text-lg"
        >
          {block.text}
        </h3>,
      );
      return;
    }

    output.push(
      <p
        key={`${block.text}-${index}`}
        className="my-3 break-words text-sm leading-6 text-slate-700 [overflow-wrap:anywhere] sm:text-[15px] sm:leading-7"
      >
        {renderText(block.text)}
      </p>,
    );
  });

  flushBullets();
  return output;
};

const PrivacyPolicy: React.FC = () => {
  return (
    <div id="top" className="min-h-screen bg-white text-slate-900">
      <header>
        <div className="mx-auto w-full max-w-5xl px-4 pb-6 pt-8 text-center sm:px-6 sm:pb-8 sm:pt-10 lg:px-8 lg:pb-10 lg:pt-12">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.16em] text-blue-700 sm:text-sm">
            AskOxy.ai Legal
          </p>

          <h1 className="text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl lg:text-[42px]">
            Privacy Policy
          </h1>

          <p className="mt-3 text-xs font-medium text-slate-500 sm:text-sm">
            Last Updated: September 23, 2026
          </p>

          <p className="mx-auto mt-6 max-w-4xl text-sm leading-7 text-slate-600 sm:text-base sm:leading-8">
            This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide, operate, secure, and improve the Service. This Privacy Policy applies to the services and features offered through Aksoxy.ai. The Personal Data collected and the purposes for which it is used may vary depending on the Service or feature used by You. Where required by applicable law, consent will be obtained separately for the specified purpose.
          </p>
        </div>
      </header>

      <main className="mx-auto w-full max-w-5xl px-4 pb-10 sm:px-6 sm:pb-12 lg:px-8 lg:pb-16">
        <article className="space-y-5 sm:space-y-6">
          {sections.map((section) => (
            <section
              key={section.id}
              id={section.id}
              className="scroll-mt-24 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"
            >
              <div className="border-b border-slate-100 px-4 py-4 sm:px-6 sm:py-5 lg:px-8">
                <div className="flex items-start gap-3">
                  <span className="flex h-8 min-w-8 shrink-0 items-center justify-center rounded-lg bg-blue-700 px-2 text-sm font-bold text-white">
                    {section.number}
                  </span>
                  <h2 className="min-w-0 text-lg font-bold leading-snug text-slate-950 sm:text-xl lg:text-2xl">
                    {section.title}
                  </h2>
                </div>
              </div>

              <div className="min-w-0 px-4 py-4 sm:px-6 sm:py-6 lg:px-8 lg:py-7">
                {renderBlocks(section.blocks)}

                <div className="mt-6 border-t border-slate-100 pt-4 text-right">
                  <a
                    href="#top"
                    className="text-xs font-semibold text-blue-700 hover:text-blue-800"
                  >
                    Back to top ↑
                  </a>
                </div>
              </div>
            </section>
          ))}
        </article>
      </main>
    </div>
  );
};

export default PrivacyPolicy;
